name: Run custom action
on : push
jobs: 
  testing-action : 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          npm install -g @actions/core
          npm install -g @actions/github
      - uses: ./.github/actions/hello
        id: hello
        with: 
          who-to-greet: "World"
      - run: |
          echo "Time  ${{ steps.hello.outputs.time }}"