name: Shell Commands

on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hellow world"
      - name: multiline script 
        run: |
          node -v
          npm -v
      - name: pythom command
        run: |
          import os
          print(os.environ['PATH'])
        shell: python
  
  windows-commands: 
    needs: [run-shell-command]
    runs-on: windows-latest
    steps:
      - name: Directory Powershell 
        run: Get-Location
      - name: Directory Bach 
        run: pwd
        shell: bash


